eventBusURL: ws://127.0.0.1:8081

logging:
  level: INFO
  loggers:
    uk.ac.gla.sed.clients: DEBUG

server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: 8080

# Database settings.
database:
  # the name of your JDBC driver
  driverClass: org.postgresql.Driver

  # the username
  user: transactionservice

  # the password
  password: transactionservice

  # the JDBC URL
  url: jdbc:postgresql://127.0.0.1:5432/transactionservice